### ISSUE TITLE
Problem when trying to authenticate

### ISSUE THREAD

**Issue by scruffyfox** [appdotnet/ADNLogin-SDK-Android#2]
Passport starts up, has a loading progress and then shows an unknown error dialog

```
09-03 23:08:22.973: E/AppDotNetResponseHandler(20707): Bad Request: invalid bundle_id (400)
09-03 23:08:22.973: E/AppDotNetResponseHandler(20707): com.alwaysallthetime.adnlib.d: Bad Request: invalid bundle_id (400)
09-03 23:08:22.973: E/AppDotNetResponseHandler(20707):  at com.alwaysallthetime.adnlib.c.c.a(SourceFile:21)
09-03 23:08:22.973: E/AppDotNetResponseHandler(20707):  at com.alwaysallthetime.adnlib.c.a(SourceFile:94)
09-03 23:08:22.973: E/AppDotNetResponseHandler(20707):  at com.alwaysallthetime.adnlib.c.doInBackground(SourceFile:19)
09-03 23:08:22.973: E/AppDotNetResponseHandler(20707):  at android.os.AsyncTask$2.call(AsyncTask.java:287)
09-03 23:08:22.973: E/AppDotNetResponseHandler(20707):  at java.util.concurrent.FutureTask.run(FutureTask.java:234)
09-03 23:08:22.973: E/AppDotNetResponseHandler(20707):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
09-03 23:08:22.973: E/AppDotNetResponseHandler(20707):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
09-03 23:08:22.973: E/AppDotNetResponseHandler(20707):  at java.lang.Thread.run(Thread.java:841)
```

**Comment by berg** [comment]
Looks like there's some server-side stuff we need to flip on still. Give me a little bit and I'll make sure it's sorted.
